apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: minio-dev
spec:
  selector:
    app: minio
  type: NodePort
  ports:
    - protocol: TCP
      port: 30000
      targetPort: 9090
      nodePort: 30000
---
apiVersion: v1
kind: Service
metadata:
  name: minio-api-service
  namespace: minio-dev
spec:
  selector:
    app: minio
  type: NodePort
  ports:
    - protocol: TCP
      port: 30001
      targetPort: 9000
      nodePort: 30002
